MySite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MySite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^note/', include('note.urls', namespace="note")),
    url(r'^admin/', include(admin.site.urls)),
)

note/urls.py
from django.conf.urls import patterns, url

from note import views


urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.article_detail, name='detail'),
    url(r'^(?P<pk>\d+)/autor/$', views.AutorView.as_view(), name='autor'),
    
)

note/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.forms import ModelForm

    
class Autor(models.Model):
    fio = models.CharField(max_length=200)
    date_birth = models.DateField('date birthday')
    bio = models.CharField(max_length=5000)
    
    def __unicode__(self):
        return self.fio


class Stat(models.Model):
    date_pub = models.DateTimeField('date published')
    name = models.CharField(max_length=200)
    about = models.TextField(max_length=1000, null=True)
    text = models.TextField(max_length=5000)
    autor = models.ForeignKey(Autor)
    
    def __unicode__(self):
        return self.name


class Comment(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    who = models.CharField(max_length=200)
    text = models.TextField(max_length=5000)
    stat = models.ForeignKey(Stat)
    
    def __unicode__(self):
        return self.who

note/forms.py
from django.forms import ModelForm
from django import forms
from django.db import models
from note.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('who', 'text',)


    

note/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import RequestContext, loader
from note.models import Autor, Stat, Comment
from note.forms import CommentForm
from django.core.urlresolvers import reverse
from django.views import generic
from django import forms
from django.forms.models import modelformset_factory
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
   

class IndexView(generic.ListView):
    template_name = 'note/index.html'
    context_object_name = 'latest_stat_list'
    queryset = Stat.objects.select_related('autor')
    paginate_by = 3
    

class AutorView(generic.DetailView):
    model = Autor
    template_name = 'note/autor.html'


class CommentView(generic.ListView):
    template_name = 'note/detail.html'
    context_object_name = 'latest_comment_list'
    queryset = Comment.objects.select_related('stat')


def article_detail(request, pk):
    article = get_object_or_404(Stat, pk=pk)
    
    form = CommentForm(data=request.POST or None)
    if form.is_valid():
        comment = form.save(commit = False)
        comment.stat = article
        comment.save()
        return redirect('note:detail', pk=pk)
    context = dict(form=form, stat=article)
    return render(request, 'note/detail.html', context)

note/templates/note/autor.html
<form action="{% url 'note:autor' autor.id %}" method="post">
{% csrf_token %}
<label for="autor{{ forloop.counter }}"><h1>{{ autor.fio }}</h1></label><br />
<label for="autor{{ forloop.counter }}"><h4>{{ autor.date_birth }}</h4></label><br />
<label for="autor{{ forloop.counter }}">{{ autor.bio }}</label><br />

</form>

note/templates/note/detail.html
<h1>{{ Stat.name }}</h1>


<label for="stat{{ forloop.counter }}"><h3>{{ stat.name }}</h3><h5> {{ stat.date_pub }} </h5></label><br>


<label for="stat{{ forloop.counter }}">{{ stat.text }}</label><br>
<a href="{% url 'note:autor' stat.autor.pk %}" target="_blank" >Об авторе... </a><br>
<a href="{% url 'note:index' %}">К списку статьей</a><br>
<hr>
Комментарии:
<ul>
{% for comment in stat.comment_set.all %}
    {{ comment.who }}:<br>
    {{ comment.text }}<br>
    {{ comment.created_on }}<hr>
{% endfor %}
</ul>
Оставьте свой комментарий: 


<form method="post">{%  csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Отправить">
</form> 

note/templates/note/index.html
{% if latest_stat_list %}
    <ul>
        {% for stat in latest_stat_list %}
    {# Each "stat" is a Stat model object. #}
    <li><a href="{% url 'note:detail' stat.id %}"> {{ stat.name }} </a>
    <a>{{ stat.date_pub }} </a><p> {{ stat.about }} <p> Автор: {{ stat.autor.fio }}</li>
     
     <hr>
        
{% endfor %}   
    </ul>
{% else %}
    <p>No stats are available.</p>
{% endif %}




<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}"><=</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">=></a>
        {% endif %}
    </span>
</div>
</div>